services:
  arozos:
    ports:
      - 8080:8080
    volumes:
      - ./run/web:/arozos/web
      - ./run/files:/arozos/files
      - ./run/system:/arozos/system
    image: ghcr.io/asdf3601a/arozos-docker:latest